name = "FoxPackDH"
author = "Augen"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6c53f587fe75a95b2ede847d42f7f1dc43f073aa7949fea318373e5b8ef0b55e"

[versions]
fabric = "0.17.2"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21"]
