name = "FoxPackDH"
author = "Augen"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fa4ce6b00480cdfa43bb373999e41ab4c85af92c7cdf8dc632fbc4877a222fe5"

[versions]
fabric = "0.17.2"
minecraft = "1.21.1"
unsup = "1.2.0-pre1"

[options]
acceptable-game-versions = ["1.21"]
