name = "FoxPackDH"
author = "Augen"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "be299816dc9299b3ada8ad5ed5a6080bcc60a6c54f37e7e064473a98d12950cf"

[versions]
fabric = "0.17.2"
minecraft = "1.21.1"
unsup = "1.2.0-pre1"

[options]
acceptable-game-versions = ["1.21"]
